/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_support_Recognition */

#ifndef _Included_com_support_Recognition
#define _Included_com_support_Recognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_support_Recognition
 * Method:    writeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_support_Recognition_writeFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_support_Recognition
 * Method:    reco
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_support_Recognition_reco
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
